### ISSUE TITLE
TR-compatible quit

### ISSUE THREAD

**Issue by peterferrie** [jeremysrand/a2bejwld#3]
We use a JMP $100 to return directly to TR without a reboot.
The current JMP ($FFFC) hits a ProDOS Quit which I didn't implement.

**Comment by jeremysrand** [comment]
I just pushed a change which should do a JMP $100 when the user quits in the TR build.  This is in the 2.2a2.tr build which I will also make available in the slack channel.

**Comment by jeremysrand** [comment]
In the end, Peter added support for ProDOS quit in Total Replay.  With this, a2bejwld no longer needs custom quit code.  Closing this issue.
