### ISSUE TITLE
(h)int at very start of game not working

### ISSUE THREAD

**Issue by tomcw** [jeremysrand/a2bejwld#4]
Hi Jeremy,

I'm using a2bejwld v2.5 (running under AppleWin 1.29.12.0, with a Mockingboard clone with speech chip).

Anyway, after starting a game, pressing 'h' just moves the cursor to the top-left of the screen, but without a move that I can make. If I make a line of 3, then 'h' starts working.

**Comment by jeremysrand** [comment]
Agreed.  I have just pushed a fix for this problem with commit e21c7375f6f067c403652d04b8cdb899abeca65c.  It isn't in a release yet but I will plan to release a v2.6 with this fix, and maybe some speech improvements...

Thanks for the bug report!
